language: go

matrix:
  include:
  -  os: linux
     sudo: required
     services:
       - docker
  -  os: osx

go:
  - 1.13.x

notifications:
  email: false

install:
  # Ideally, the (brew update) should not be necessary and Travis would have fairly
  # frequenstly updated OS images; thatâ€™s not been the case historically.
  # In particular, explicitly unlink python@2, which has been removed from Homebrew
  # since the last OS image build (as of July 2020), but the Travis OS still
  # contains it, and it prevents updating of Python 3.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew unlink python@2 && brew install gpgme ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then hack/travis_osx.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make vendor && ./hack/tree_status.sh && make check ; fi
